fix a typing error: json.load(p, encoding='utf-8') takes no encoding
According to the 'json' documentation, json.load never took an
encoding parameter, json.loads (load string) had one until
3.9. I guess that recently the checks for irrelevant parameters got
stricter, this causes a failure on my Python 3.9 setup:

```
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

fixes #50